### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by ludos1978** [matthijsgroen/geppetto#5]
Hi, the download link to osx x86 is broken on the page https://geppetto.js.org/ .
it currently links to:
https://github.com/matthijsgroen/geppetto/releases/download/1.2.0/Geppetto-1.2.0-mac.dmg
correct would be:
https://github.com/matthijsgroen/geppetto/releases/download/1.2.0/Geppetto-1.2.0.dmg
best

**Comment by matthijsgroen** [comment]
Thanks for reporting!
